[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = { workspace = true }
clap = { version = "4.3.0", features = ["derive"] }

scanner.path = "../lib/scanner"
parser.path = "../lib/parser"
