[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = { workspace = true }
clap = { version = "4.3.0", features = ["derive"] }
itertools.workspace = true

scanner.path = "../lib/scanner"
compiler.path = "../lib/compiler"
vm.path = "../lib/vm"

log.workspace = true
env_logger = "0.10.0"

[dev-dependencies]
lazy-regex = "3.1.0"
pretty_assertions.workspace = true
ctor.workspace = true
test_suite_proc_macro.path = "tests/test_suite_proc_macro"
